# Generated by Django 4.1.2 on 2022-11-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.CharField(max_length=50, verbose_name='Página')),
                ('title', models.CharField(max_length=100, verbose_name='Producto-Titulo')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
            ],
        ),
    ]
