# Generated by Django 4.1.3 on 2022-11-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionScrapers', '0002_remove_product_brand_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link'),
        ),
    ]
